### ISSUE TITLE
A few bugs found in "Branch:Master" files dated 05-29-2011.

### ISSUE THREAD

**Issue by arttronics** [mjackson/shadowbox#20]
These are the fixes I am using to be able to build the latest release of Shadowbox.
<br/>
Notes:            This correction will allow Shadowbox to be initialized via Shadowbox.init. Error attributed to 'contains'.
Correction Done:  Used Stable Release v3.0.3 source method to temporarily fix this condition.
File:             source\plugins.js

<p><code>- 21        fla:    names.contains('Shockwave Flash'),</code></p>

<p><code>- 22        qt:     names.contains('QuickTime')</code></p> 

<p><code>+ 21        fla:    names.indexOf('Shockwave Flash') > -1,</code></p>

<p><code>+ 22        qt:     names.indexOf('QuickTime') > -1</code></p>

<br/>
Notes:            Test 12: cache module: select (with a CSS selector) (1, 0, 1)
Correction Done:  Removed specific test due to CSS Support that has been removed.
File:             tests\unit\cache.js

<p><code>- 26          test("select (with a CSS selector)", function() {</code></p>

<p><code>- 27              var sel = Shadowbox.select("#main a");</code></p>

<p><code>- 28              equal(sel.length, 4, "Select multiple elements when given a CSS selector");</code></p>

<p><code>- 29          });</code></p>

<br/>
Notes:            Current Version Detection contains incomplete string, causing text editor "syntax highlighting" for Ruby Filetypes to show incorrectly.
Correction Done:  Used Stable Release v3.0.3 source method to temporarily fix this condition.
File:             tools\shadowbox.rb

<p><code>- 11 f.read.match(/version: (['"])([\w.]+)\1/)[2]</code></p></p>

<p><code>+ 11 f.read.match(/version: ['"]([\w.]+)['"]/)[1]</code></p></p>

<br/>
Notes:            Shadowbox non-text "Build" files obtained from valid files in "source/resources" are corrupt after custom build of Shadowbox.
Correction Done:  Temporarily excluded via # file copy process and used copies manually made from the "source/resources" folder (.png, .swf, and .gif)
File:             tools\shadowbox.rb

<p><code>- 105   resource_files.each do |file|</code></p>

<p><code>- 106   target[File.basename(file)] = File.read(file)</code></p>

<p><code>- 107   end</code></p>

<p><code>+ 105   # resource_files.each do |file|</code></p>

<p><code>+ 106   # target[File.basename(file)] = File.read(file)</code></p>

<p><code>+ 107   # end</code></p>

**Comment by brgrz** [comment]
Do the fixes we post here ever get it into Shadowbox release? Coz I'm not seeing any response from the author..

**Comment by arttronics** [comment]
Branch Master versions are not to be used as they are works in progress.

When your looking at stable release v3.0.3 for example, it was last updated at the end of May.

If you are looking at Branch Master v4.00 you will see the author is actively working on the next Shadowbox version as stated in this Read Me:
https://github.com/mjijackson/shadowbox/blob/v4/README

The changes provided at this site may or may not be introduced in a future version of Shadowbox, but nevertheless they are presented here so that others can build there custom version since the author may consider some changes "hacks" that have security issues or do not work with every browser the author requires them to work in.

As for this thread, I now noticed that someone else has previously post a fix to build the BUILD the Branch Master of Shadowbox that when compared to my method, is much simpler to do. That fix which also includes a Commit Link is located here:
https://github.com/mjijackson/shadowbox/pull/16

If you have any installation or issues with using Shadowbox please visit the Shadowbox forum web-site here:
http://www.shadowbox-js.com/forum.html

This thread is now closed since Master Branch is not meant to be a stable release and will contain bugs.

Feel free to post a new thread here at GitHub for any known bugs in stable releases that you find.
