### ISSUE TITLE
Flash components appearing in front of images in shadowbox 3.0.2

### ISSUE THREAD

**Issue by RAYPHC** [mjackson/shadowbox#4]
I noticed a problem when you have flash imbedded on a page and then you open an image using shadowbox, the flash components  will be above (in front) of your image ???

I tried it in chrome fire fox and IE and the same result, the flash components will be above (in front) of the image when it open with shadowbox?? 
I added the new shadowbox 3.0.2 to my website to show you the problem, please click on the link http://phc.ps/MediaNews/index.html   then click on any image; you will see the audio player in front of the image. 
Thank you for your help

**Comment by level420** [comment]
@RAYPHC: I had the same effect. Setting the flash object attribute 'vmode' to value 'opaque' solved this problem for me:

http://kb2.adobe.com/cps/127/tn_12701.html

**Comment by RAYPHC** [comment]
thank you it worked
